Update build-kernel-ksu.yml

diff --git a/.github/workflows/build-kernel-ksu.yml b/.github/workflows/build-kernel-ksu.yml
--- a/.github/workflows/build-kernel-ksu.yml
+++ b/.github/workflows/build-kernel-ksu.yml
@@ -5,7 +5,7 @@ env:
   CLANG_DIR: clang-r584948b
 jobs:
   build-ksu:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
     steps:
       - name: Free Disk Space (Ubuntu)
         if: ${{ true }} # Set to true if space insufficient
@@ -72,15 +72,17 @@ jobs:
           cd kernel_platform/xiaomi/sm8450
 
           # очистить старое
-          rm -rf drivers/kernelsu drivers/KernelSU KernelSU
+          rm -rf drivers/kernelsu
 
           # клонировать KernelSU
-          git clone https://github.com/tiann/KernelSU.git drivers/kernelsu
+          git clone --depth=1 https://github.com/tiann/KernelSU.git drivers/kernelsu
           cd drivers/kernelsu
+          git fetch --depth=1 origin 92aff05
           git checkout 92aff05
           cd ../..
 
-          # подключить Kconfig (если ещё не подключён)
+          test -f drivers/kernelsu/Kconfig || (echo "Kconfig missing" && exit 1)
+
           if ! grep -q "drivers/kernelsu/Kconfig" drivers/Kconfig; then
           echo 'source "drivers/kernelsu/Kconfig"' >> drivers/Kconfig
           fi
