Update build-kernel-ksu-susfs.yml

diff --git a/.github/workflows/build-kernel-ksu-susfs.yml b/.github/workflows/build-kernel-ksu-susfs.yml
--- a/.github/workflows/build-kernel-ksu-susfs.yml
+++ b/.github/workflows/build-kernel-ksu-susfs.yml
@@ -71,12 +71,11 @@ jobs:
           check_v2_signature(path, 0x363, "4359c171f32543394cbc23ef908c4bb94cad7c8087002ba164c8230948c21549") /*backslashxx*/ || \\ \
           check_v2_signature(path, 0x396, "f415f4ed9435427e1fdf7f1fccd4dbc07b3d6b8751e4dbcec6f19671f427870b") /*rsuntk*/;' "$FILE"
 
-          if grep -q "4359c171f32543394cbc23ef908c4bb94cad7c8087002ba164c8230948c21549" "$FILE" && \
-             grep -q "f415f4ed9435427e1fdf7f1fccd4dbc07b3d6b8751e4dbcec6f19671f427870b" "$FILE"; then
-            echo "Patch applied successfully. File content:"
-            grep -A 5 "return check_v2_signature" "$FILE"
+          if grep -q "4359c171f32543394cbc23ef908c4bb94cad7c8087002ba164c8230948c21549" "$FILE"; then
+            echo "Patch success. Preview:"
+            grep -A 3 "return check_v2_signature" "$FILE"
           else
-            echo "Patch failed! Check if the file exists and the search string matches." && exit 1
+            echo "Patch failed!" && exit 1
           fi
       - name: Include personal changes
         run: |
