Update build-kernel-ksu-susfs.yml

diff --git a/.github/workflows/build-kernel-ksu-susfs.yml b/.github/workflows/build-kernel-ksu-susfs.yml
--- a/.github/workflows/build-kernel-ksu-susfs.yml
+++ b/.github/workflows/build-kernel-ksu-susfs.yml
@@ -63,7 +63,7 @@ jobs:
           patch -p1 < 10_enable_susfs_for_ksu.patch
           cd ..
           patch -p1 < 50_add_susfs_in_gki-android12-5.10.patch
-      - name: Include other KSU manager signatures
+      - name: Include other KernelSU managers signatures
         run: |
           FILE="kernel_platform/xiaomi/sm8450/KernelSU/kernel/apk_sign.c"
           sed -i 's/return check_v2_signature(path, EXPECTED_SIZE, EXPECTED_HASH);/return check_v2_signature(path, EXPECTED_SIZE, EXPECTED_HASH) || \\/g' "$FILE"
@@ -73,9 +73,10 @@ jobs:
 
           if grep -q "4359c171f32543394cbc23ef908c4bb94cad7c8087002ba164c8230948c21549" "$FILE" && \
              grep -q "f415f4ed9435427e1fdf7f1fccd4dbc07b3d6b8751e4dbcec6f19671f427870b" "$FILE"; then
-            echo "Patch applied successfully"
+            echo "Patch applied successfully. File content:"
+            grep -A 5 "return check_v2_signature" "$FILE"
           else
-            echo "Patch failed!" && exit 1
+            echo "Patch failed! Check if the file exists and the search string matches." && exit 1
           fi
       - name: Include personal changes
         run: |
